apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-leader-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/ec2-user/guestbook-redis/leader
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: supermaster
          operator: In
          values:
          - "yes"
